name: Deploy Homolog

on:
  workflow_call:
    inputs:
      environment-name:
        type: string
        required: true
      environment-url:
        type: string
        required: true  

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::618289386271:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Configure EKS
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name eks-lab

      - name: Update Deployment
        run: "sed -i 's/host: homologacao.fabricioveronez.com/host: ${{ vars.BASE_URL }}/g' k8s/deployment.yaml"

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml

      - name: Update application image
        run: |
          kubectl set image deployment/reviewfilmes \
            reviewfilmes=lucascardoso1/devops-project-pro:v${{ github.run_number }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/reviewfilmes --timeout=180s

      - name: Check resources
        run: |
          kubectl get pods
          kubectl get deployments
          kubectl get services